name: Update README with GitHub activity (weekly)

on:
  schedule:
    - cron: "0 9 1 * *"  # First of every month
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update recent GitHub activity
        uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          GH_USERNAME: ErikBurton
          COMMIT_MSG: "docs: update Monthly GitHub activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

